// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAprgEYnKStO1oJHjeaR-CaO_DDU0F9gNA',
    appId: '1:499894767485:web:8dc41c4e6d03513043c614',
    messagingSenderId: '499894767485',
    projectId: 'devathon-project-9bb21',
    authDomain: 'devathon-project-9bb21.firebaseapp.com',
    storageBucket: 'devathon-project-9bb21.appspot.com',
    measurementId: 'G-SRHTG3X5GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD746Fd62BdMED9bUh-vqC-4EGEyQF96AM',
    appId: '1:499894767485:android:1a24f508d2e0b2e943c614',
    messagingSenderId: '499894767485',
    projectId: 'devathon-project-9bb21',
    storageBucket: 'devathon-project-9bb21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD15Rh3q7e0lLmiosGW2g_uWX2lSlpYQWw',
    appId: '1:499894767485:ios:43c01450f9f9f1e443c614',
    messagingSenderId: '499894767485',
    projectId: 'devathon-project-9bb21',
    storageBucket: 'devathon-project-9bb21.appspot.com',
    iosBundleId: 'com.example.devhathon',
  );
}
